name: Pose Estimation Server for GPU
on:
 push:
   branches:
     - gpu
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Publish Image
      uses: matootie/github-docker@v3.0.0
      with:
        accessToken: ${{ secrets.TOKEN }}
        tag: |
          latest
          ${{github.sha}}
        imageName: pose-estimation-gpu
